Repository Apodini/Apodini, pull requests merged in 2020-12, with the labels that each got.

#36 Fix #34: add preconditions checking that components are structs
  Sources/Apodini/Components/Component.swift
  Sources/Apodini/Modifier/GuardModifier.swift
  Sources/Apodini/Modifier/ResponseModifer.swift
  Sources/Apodini/Request/RequestInjectable.swift
Labels: enhancement

#38 Fix SPM Warning
  Package.swift
Labels: enhancement

#49 Add codecov
  .github/workflows/swift.yml
  README.md
Labels: enhancement

#52 Create codecov.yml
  codecov.yml
Labels: enhancement

#65 Add badges for documentation and CI
  README.md
Labels: documentation

#27 Documentation/push notifications
  Documentation/AdditionalFunctionality/Jobs.md
  Documentation/AdditionalFunctionality/PushNotifications.md
  Documentation/Communicational Patterns/2. Tooling/2.3. State.md
  Documentation/Communicational Patterns/2. Tooling/2.4. ObservedObject.md
  Documentation/Communicational Patterns/2. Tooling/2.5. Environment.md
Labels: documentation

#67 @_implementationOnly import Runtime and AssociatedTypeRequirementsVisitor
  Sources/Apodini/Components/Component.swift
  Sources/Apodini/Modifier/GuardModifier.swift
  Sources/Apodini/Request/RequestInjectable.swift
  Sources/Apodini/SyntaxTreeVisitor/SyntaxTreeVisitor+unsafeVisit.swift
  Sources/ProtobufferCoding/ProtoCodingKey.swift
Labels: enhancement

#69 Fix crash when creating RestRequest from a Vapor.Request without a db
  Sources/Apodini/Semantic Model Builder/REST/RESTInterfaceExporter.swift
  Tests/ApodiniTests/SharedSemanticModelBuilderTests.swift
Labels: bug

#78 Create pull_request_template.md
  .github/pull_request_template.md
Labels: enhancement

#77 Tame Codecov
  codecov.yml
Labels: enhancement
