Repository Apodini/Apodini, pull requests merged in 2021-06, with the labels that each got.

#284 [Bug] TLS Configuration not possible when configuring database
  Sources/ApodiniDatabase/Context/DatabaseConfiguration.swift
Labels: bug

#290 Allow Apodini to be used with semantic versioning
  Package.swift
Labels: bug

#300 Binary Large Objects
  Package.resolved
  Package.swift
  Sources/Apodini/Application/Application.swift
  Sources/Apodini/Response/Blob.swift
  Sources/Apodini/Response/Empty.swift
  Sources/Apodini/Response/MimeType.swift
  Sources/Apodini/Response/Response.swift
  Sources/Apodini/Semantic Model Builder/InterfaceExporter/InterfaceExporterVisitor.swift
  Sources/ApodiniDatabase/Handlers/Update/Updater.swift
  Sources/ApodiniOpenAPI/Document/OpenAPIComponentsObjectBuilder.swift
  Sources/ApodiniREST/RESTEndpointHandler.swift
  Sources/ApodiniREST/ResponseContainer.swift
  Sources/ApodiniVaporSupport/Application+Vapor.swift
  Sources/ApodiniVaporSupport/HTTPStatus+Status.swift
  Sources/XCTApodini/Mocks/MockExporter.swift
  Sources/XCTApodini/XCTAssertRuntimeFailure.swift
  Tests/ApodiniTests/ApplicationTests/ApplicationTests.swift
  Tests/ApodiniTests/Helper/Blob+Equatable.swift
  Tests/ApodiniTests/ResponseTests/BlobTests.swift
Labels: enhancement

#301 Information for Requests and Responses
  Package.swift
  Sources/Apodini/Application/Application+Connection.swift
  Sources/Apodini/Information/AnyInformation.swift
  Sources/Apodini/Information/Authorization.swift
  Sources/Apodini/Information/Cookies.swift
  Sources/Apodini/Information/ETag.swift
  Sources/Apodini/Information/Expires.swift
  Sources/Apodini/Information/Information.swift
  Sources/Apodini/Information/RedirectTo.swift
  Sources/Apodini/Information/Set+Information.swift
  Sources/Apodini/Properties/Options/HTTPParameterMode.swift
  Sources/Apodini/Properties/Request.swift
  Sources/Apodini/Response/Response.swift
  Sources/Apodini/Response/Status.swift
  Sources/Apodini/Semantic Model Builder/InterfaceExporter/ConnectionContext.swift
  Sources/Apodini/Semantic Model Builder/InterfaceExporter/ExporterRequest.swift
  Sources/Apodini/Semantic Model Builder/InterfaceExporter/ValidatingRequest.swift
  Sources/Apodini/Semantic Model Builder/InterfaceExporter/Validator.swift
  Sources/Apodini/Semantic Model Builder/Model/EndpointParameter.swift
  Sources/Apodini/Semantic Model Builder/Model/ParameterNamespace.swift
  Sources/Apodini/Semantic Model Builder/Model/ParameterType.swift
  Sources/ApodiniDeploy/ApodiniDeployInterfaceExporter.swift
  Sources/ApodiniOpenAPI/Document/OpenAPIComponentsObjectBuilder.swift
  Sources/ApodiniOpenAPI/Extensions/OpenAPIParameterContext+AnyEndpointParameter.swift
  Sources/ApodiniREST/RESTEndpointHandler.swift
  Sources/ApodiniREST/RESTInterfaceExporter.swift
  Sources/ApodiniREST/ResponseContainer.swift
  Sources/ApodiniVaporSupport/HTTPHeaders+InformationKeys.swift
  Sources/ApodiniVaporSupport/HTTPMethod+Operation.swift
  Sources/ApodiniVaporSupport/HTTPStatus+Status.swift
  Sources/ApodiniVaporSupport/Request+ExporterRequestWithEventLoop.swift
  Sources/ApodiniVaporSupport/ResponseContainer.swift
  Sources/ApodiniWebSocket/WebSocketInterfaceExporter.swift
  Tests/ApodiniTests/InformationTests/InformationRequestTests.swift
  Tests/ApodiniTests/InformationTests/InformationResponseTests.swift
  Tests/ApodiniTests/InformationTests/InformationTests.swift
  Tests/ApodiniTests/OpenAPITests/OpenAPIComponentsObjectBuilderTests.swift
  Tests/ApodiniTests/OpenAPITests/OpenAPIDocumentBuilderTests.swift
  Tests/ApodiniTests/SemanticModel/ParameterNamespaceTests.swift
Labels: enhancement, needs version bump

#302 Fix Propagation of Delegate Optionality
  Sources/Apodini/Properties/Delegate.swift
  Sources/Apodini/Semantic Model Builder/Traversable.swift
  Tests/ApodiniTests/DelegationTests.swift
  Tests/ApodiniTests/SemanticModel/ParameterMutabilityTests.swift
Labels: bug

#299 Remove Relationship Code from `SemanticModelBuilder`
  Sources/Apodini/Components/Handler/HandlerIdentifier.swift
  Sources/Apodini/Properties/Binding.swift
  Sources/Apodini/Response/Response.swift
  Sources/Apodini/Semantic Model Builder/EndpointsTree.swift
  Sources/Apodini/Semantic Model Builder/InterfaceExporter/ConnectionContext.swift
  Sources/Apodini/Semantic Model Builder/InterfaceExporter/RequestHandler.swift
  Sources/Apodini/Semantic Model Builder/InterfaceExporter/Validator.swift
  Sources/Apodini/Semantic Model Builder/KnowledgeSource.swift
  Sources/Apodini/Semantic Model Builder/KnowledgeSources/HandlerKnowledge.swift
  Sources/Apodini/Semantic Model Builder/KnowledgeSources/HandlerKnowledgeSource.swift
  Sources/Apodini/Semantic Model Builder/KnowledgeSources/LoggerKnowledge.swift
  Sources/Apodini/Semantic Model Builder/KnowledgeSources/PathKnowledge.swift
  Sources/Apodini/Semantic Model Builder/KnowledgeSources/RelationshipKnowledge.swift
  Sources/Apodini/Semantic Model Builder/KnowledgeSources/ResponseTypeKnowledge.swift
  Sources/Apodini/Semantic Model Builder/Model/Endpoint.swift
  Sources/Apodini/Semantic Model Builder/Model/EndpointPath.swift
  Sources/Apodini/Semantic Model Builder/Model/EndpointReference.swift
  Sources/Apodini/Semantic Model Builder/Model/EndpointsTreeNode+Collectable.swift
  Sources/Apodini/Semantic Model Builder/Model/WebServiceModel.swift
  Sources/Apodini/Semantic Model Builder/Relationship/EndpointRelationship.swift
  Sources/Apodini/Semantic Model Builder/Relationship/PathParameterResolver.swift
  Sources/Apodini/Semantic Model Builder/Relationship/RelationshipBuilder.swift
  Sources/Apodini/Semantic Model Builder/Relationship/RelationshipCandidate.swift
  Sources/Apodini/Semantic Model Builder/Relationship/RelationshipEndpoint.swift
  Sources/Apodini/Semantic Model Builder/Relationship/RelationshipFormatter.swift
  Sources/Apodini/Semantic Model Builder/Relationship/RelationshipInstance.swift
  Sources/Apodini/Semantic Model Builder/Relationship/RelationshipModule.swift
  Sources/Apodini/Semantic Model Builder/Relationship/RelationshipWebServiceModel.swift
  Sources/Apodini/Semantic Model Builder/SemanticModelBuilder.swift
  Sources/ApodiniDatabase/Context/DatabaseConfiguration.swift
  Sources/ApodiniDeploy/RemoteHandlerInvocationManager.swift
  Sources/ApodiniGRPC/GRPCService/GRPCServiceClientStreaming.swift
  Sources/ApodiniGRPC/GRPCService/GRPCServiceUnary.swift
  Sources/ApodiniOpenAPI/Document/OpenAPIPathsObjectBuilder.swift
  Sources/ApodiniREST/EnrichedContent.swift
  Sources/ApodiniREST/RESTEndpointHandler.swift
  Sources/ApodiniREST/RESTInterfaceExporter.swift
  Sources/ApodiniWebSocket/WebSocketInterfaceExporter.swift
  Sources/XCTApodini/Mocks/MockBlackboard.swift
  Sources/XCTApodini/Mocks/MockEndpoint.swift
  Tests/ApodiniDeployTests/LambdaDeploymentProviderTests.swift
  Tests/ApodiniTests/ComponentTests/EmptyComponentTests.swift
  Tests/ApodiniTests/DelegationTests.swift
  Tests/ApodiniTests/GRPCInterfaceExporterTests.swift
  Tests/ApodiniTests/MetadataTests/BuildinMetadata/DescriptionMetadataTests.swift
  Tests/ApodiniTests/MetadataTests/ComponentMetadataTests.swift
  Tests/ApodiniTests/OpenAPITests/OpenAPIDocumentBuilderTests.swift
  Tests/ApodiniTests/OpenAPITests/OpenAPIPathsObjectBuilderTests.swift
  Tests/ApodiniTests/OpenAPITests/TagModifierTests.swift
  Tests/ApodiniTests/PropertiesTests/ObservedObjectTests.swift
  Tests/ApodiniTests/RESTInterfaceExporterTests.swift
  Tests/ApodiniTests/RelationshipTests/Infrastructure/RelationshipExporter.swift
  Tests/ApodiniTests/RelationshipTests/Infrastructure/RelationshipTestContext.swift
  Tests/ApodiniTests/ResponseTests/BlobTests.swift
  Tests/ApodiniTests/SemanticModel/EndpointsTreeTests.swift
  Tests/ApodiniTests/SemanticModel/SemanticModelBuilderTests.swift
  Tests/ApodiniTests/SyntaxTreeVisitorTests/EndpointIdentifierTests.swift
  Tests/ApodiniTests/UniqueIdentifierTests.swift
Labels: enhancement, needs version bump
