Repository Apodini/Apodini, pull requests merged in 2021-07, with the labels that each got.

#294 Update Package to Swift 5.4
  .github/pull_request_template.md
  .github/release-drafter.yml
  .github/workflows/build-and-test.yml
  .github/workflows/docs.yml
  .github/workflows/release-drafter.yml
  .github/workflows/test-webservice.yml
  Package.resolved
  Package.swift
  Sources/Apodini/Components/ComponentBuilder.swift
  Sources/Apodini/Components/ComponentBuilder.swift.gyb
  Sources/Apodini/Components/Handler/Handler.swift
  Sources/Apodini/Components/Path/PathComponentBuilder.swift
  Sources/Apodini/Configurations/ConfigurationBuilder.swift
  Sources/Apodini/Relationships/RelationshipIdentificationBuilder.swift
  Sources/Apodini/Semantic Model Builder/KnowledgeSources/RelationshipKnowledge.swift
  Sources/Apodini/SyntaxTreeVisitor/ContextNode.swift
  Sources/ApodiniDatabase/Context/DatabaseConfiguration.swift
  Sources/ApodiniDeployTestWebService/ApodiniDeployTestWebService.swift
  Sources/ApodiniDeployTestWebService/Handler.swift
  Sources/ApodiniGRPC/GRPCDependentStaticConfigurationBuilder.swift
  Sources/ApodiniGRPC/GRPCService/GRPCServiceUnary.swift
  Sources/ApodiniJobs/Schedule.swift
  Sources/ApodiniJobs/Scheduler.swift
  Sources/ApodiniREST/RESTDependentStaticConfigurationBuilder.swift
  Sources/DeploymentTargetAWSLambda/AWSIntegration.swift
  Sources/DeploymentTargetAWSLambda/Context.swift
  Sources/DeploymentTargetAWSLambda/LambdaDeploymentProviderCLI.swift
  Sources/DeploymentTargetLocalhost/LocalhostDeploymentProvider.swift
  TestWebService/Package.resolved
  TestWebService/Package.swift
  TestWebService/Sources/TestWebService/TestWebService.swift
  TestWebService/Tests/LinuxMain.swift
  Tests/ApodiniDeployTests/ApodiniDeployInterfaceExporterTests.swift
  Tests/ApodiniDeployTests/ApodiniDeployTestCase.swift
  Tests/ApodiniDeployTests/DeploymentOptionsTests.swift
  Tests/ApodiniJobsTests/Helper.swift
  Tests/ApodiniJobsTests/JobsTests.swift
  Tests/ApodiniJobsTests/ObservedObjectTests.swift
  Tests/ApodiniTests/OpenAPITests/OpenAPIComponentsObjectBuilderTests.swift
  Tests/ApodiniTests/OpenAPITests/OpenAPIPathsObjectBuilderTests.swift
  Tests/ApodiniTests/ProtobufferBuilderTests.swift
  Tests/LinuxMain.swift
Labels: experimental, needs version bump

#303 Rework ContextNode infrastructure to accommodate for extended requirements
  Documentation/Communicational Patterns/3. Pattern Implementation/3.3. Client-Side Stream.md
  Sources/Apodini/Components/Component/BaseComponents/Group.swift
  Sources/Apodini/Components/Component/Component.swift
  Sources/Apodini/Components/Handler/IdentifiableHandler.swift
  Sources/Apodini/Information/Expires.swift
  Sources/Apodini/Metadata/BuiltinMetadata/DescriptionMetadata.swift
  Sources/Apodini/Metadata/BuiltinMetadata/EmptyMetadata.swift
  Sources/Apodini/Metadata/BuiltinMetadata/OperationMetadata.swift
  Sources/Apodini/Metadata/BuiltinMetadata/ServiceTypeMetadata.swift
  Sources/Apodini/Metadata/Extensions/Context+Metadata.swift
  Sources/Apodini/Metadata/MetadataDefinition.swift
  Sources/Apodini/Metadata/Modifier/ComponentMetadataModifier.swift
  Sources/Apodini/Metadata/Modifier/HandlerMetadataModifier.swift
  Sources/Apodini/Modifier/DelegationFilterModifier.swift
  Sources/Apodini/Modifier/DelegationModifier.swift
  Sources/Apodini/Modifier/Modifier.swift
  Sources/Apodini/Modifier/OperationModifier.swift
  Sources/Apodini/Modifier/ServiceTypeModifier.swift
  Sources/Apodini/Relationships/Metadata/RelationshipInheritance.swift
  Sources/Apodini/Relationships/Metadata/RelationshipReference.swift
  Sources/Apodini/Relationships/Metadata/RelationshipSource.swift
  Sources/Apodini/Relationships/Modifier/DefaultRelationshipModifier.swift
  Sources/Apodini/Relationships/Modifier/RelationshipDestinationModifier.swift
  Sources/Apodini/Relationships/Modifier/RelationshipSourceModifier.swift
  Sources/Apodini/Relationships/Modifier/TypedRelationshipDestinationModifier.swift
  Sources/Apodini/Relationships/RelationshipSourceCandidateContextKey.swift
  Sources/Apodini/Semantic Model Builder/KnowledgeSources/HandlerKnowledge.swift
  Sources/Apodini/Semantic Model Builder/PathModelBuilder.swift
  Sources/Apodini/SyntaxTreeVisitor/Context/Context.swift
  Sources/Apodini/SyntaxTreeVisitor/Context/ContextEntry.swift
  Sources/Apodini/SyntaxTreeVisitor/Context/ContextEntryCollection.swift
  Sources/Apodini/SyntaxTreeVisitor/Context/ContextKey.swift
  Sources/Apodini/SyntaxTreeVisitor/Context/ContextNode.swift
  Sources/Apodini/SyntaxTreeVisitor/ContextNode.swift
  Sources/Apodini/SyntaxTreeVisitor/SyntaxTreeVisitor.swift
  Sources/Apodini/Utilities/Array+AnyArray.swift
  Sources/Apodini/Utilities/KeyPath+Toggle.swift
  Sources/Apodini/Utilities/Tree.swift
  Sources/ApodiniDeploy/ApodiniDeployExporterConfiguration.swift
  Sources/ApodiniGRPC/GRPCMethodNameModifier.swift
  Sources/ApodiniGRPC/GRPCServiceNameModifier.swift
  Sources/ApodiniOpenAPI/Document/OpenAPIPathsObjectBuilder.swift
  Sources/ApodiniOpenAPI/Modifier/TagModifier.swift
  Sources/XCTApodini/Mocks/MockEndpoint.swift
  Tests/ApodiniTests/GRPCInterfaceExporterTests.swift
  Tests/ApodiniTests/MetadataTests/BuildinMetadata/DescriptionMetadataTests.swift
  Tests/ApodiniTests/MetadataTests/ComponentMetadataTests.swift
  Tests/ApodiniTests/MetadataTests/ComponentOnlyMetadataTests.swift
  Tests/ApodiniTests/MetadataTests/ContentMetadataTests.swift
  Tests/ApodiniTests/MetadataTests/HandlerMetadataTests.swift
  Tests/ApodiniTests/MetadataTests/WebServiceMetadataTests.swift
  Tests/ApodiniTests/ModifierTests/OperationModifierTests.swift
  Tests/ApodiniTests/SyntaxTreeVisitorTests/ContextNodeTests.swift
Labels: needs version bump

#323 Simplify the Database Configuration
  .github/workflows/reuseaction.yml
  .github/workflows/swiftlint.yml
  Package.resolved
  Package.swift
  Sources/ApodiniDatabase/Application+Databases.swift
  Sources/ApodiniDatabase/Context/DatabaseConfiguration.swift
  Sources/ApodiniDatabase/Context/DatabaseInjectionContext.swift
  Sources/ApodiniDatabase/DatabaseModel.swift
  Sources/ApodiniDatabase/Handlers/Create/Create.swift
  Sources/ApodiniDatabase/Handlers/Create/CreateAll.swift
  Sources/ApodiniDatabase/Handlers/Delete.swift
  Sources/ApodiniDatabase/Handlers/Read/QueryBuilder.swift
  Sources/ApodiniDatabase/Handlers/Read/ReadAll.swift
  Sources/ApodiniDatabase/Handlers/Read/ReadOne.swift
  Sources/ApodiniDatabase/Handlers/Update/Update.swift
  Sources/ApodiniDatabase/Handlers/Update/Updater.swift
  Sources/ApodiniDatabase/PropertyVisitors/UpdatableFieldProperty.swift
  Sources/ApodiniDatabase/PropertyVisitors/VisitableFieldProperty.swift
  Sources/ApodiniNotifications/Models/Device.swift
  Sources/ApodiniNotifications/NotificationCenter.swift
  TestWebService/Package.resolved
  Tests/ApodiniNotificationsTests/DatabaseSchemaCreation.swift
  Tests/ApodiniNotificationsTests/NotificationCenterTests.swift
  Tests/ApodiniTests/ComponentTests/ThrowingHandlerTests.swift
  Tests/ApodiniTests/ConfigurationTests/DatabaseConfigurationTests.swift
  Tests/ApodiniTests/EnvironmentTests/DatabaseEnvironmentTests.swift
  Tests/ApodiniTests/ModifierTests/GuardTests.swift
Labels: enhancement, needs version bump
