Repository Apodini/Apodini, pull requests merged in 2021-08, with the labels that each got.

#328 Advanced `Delegate` example for TestWebService
  Sources/Apodini/Properties/Delegate.swift
  Sources/ApodiniAuthorization/AuthorizedProperty.swift
  TestWebService/Package.resolved
  TestWebService/Sources/TestWebService/TestWebService.swift
  TestWebService/Sources/TestWebService/WeatherSubsystem/Components/WeatherComponent.swift
  TestWebService/Sources/TestWebService/WeatherSubsystem/Components/WeatherInformationComponent.swift
  TestWebService/Sources/TestWebService/WeatherSubsystem/Handlers/DangerHandler.swift
  TestWebService/Sources/TestWebService/WeatherSubsystem/Handlers/TemperatureHandler.swift
  TestWebService/Sources/TestWebService/WeatherSubsystem/RouteModifier.swift
  TestWebService/Sources/TestWebService/WeatherSubsystem/Services/RouteService.swift
  TestWebService/Sources/TestWebService/WeatherSubsystem/Services/TemperatureService.swift
  Tests/ApodiniTests/DelegationTests.swift
Labels: documentation, enhancement

#330 Apodini Observe (for logging)
  Package.swift
  Sources/Apodini/Application/Application+Connection.swift
  Sources/Apodini/Information/InformationClass.swift
  Sources/Apodini/Information/StringKeyedCodableInformationClass.swift
  Sources/Apodini/Information/StringKeyedStringInformationClass.swift
  Sources/Apodini/Metadata/BuiltinMetadata/CommunicationalPatternMetadata.swift
  Sources/Apodini/Metadata/BuiltinMetadata/ServiceTypeMetadata.swift
  Sources/Apodini/Properties/Delegate.swift
  Sources/Apodini/Properties/Environment.swift
  Sources/Apodini/Properties/Options/HTTPParameterMode.swift
  Sources/Apodini/Properties/Options/PropertyOptionKey.swift
  Sources/Apodini/Properties/Options/PropertyOptionSet.swift
  Sources/Apodini/Properties/PathParameter.swift
  Sources/Apodini/Semantic Model Builder/InterfaceExporter/InterfaceExporter.swift
  Sources/Apodini/Semantic Model Builder/KnowledgeSources/All.swift
  Sources/Apodini/Semantic Model Builder/KnowledgeSources/DelegateFactory.swift
  Sources/Apodini/Semantic Model Builder/Model/EndpointParameter.swift
  Sources/Apodini/Semantic Model Builder/Traversable.swift
  Sources/Apodini/Utilities/ArgumentParserStoreable.swift
  Sources/Apodini/Version.swift
  Sources/Apodini/WebService.swift
  Sources/ApodiniDeploy/RemoteHandlerInvocationManager.swift
  Sources/ApodiniExtension/RequestDecoding/RequestDecoding.swift
  Sources/ApodiniGRPC/GRPCInterfaceExporter.swift
  Sources/ApodiniGRPC/GRPCService/GRPCServiceClientStreaming.swift
  Sources/ApodiniGRPC/GRPCService/GRPCServiceUnary.swift
  Sources/ApodiniHTTP/ClosureBuilders/HTTP1Compatibility/BidirectionalStreaming.swift
  Sources/ApodiniHTTP/ClosureBuilders/HTTP1Compatibility/ClientSideStreaming.swift
  Sources/ApodiniHTTP/ClosureBuilders/HTTP1Compatibility/ServiceSideStreaming.swift
  Sources/ApodiniHTTP/ClosureBuilders/RequestResponse.swift
  Sources/ApodiniHTTPProtocol/Information/Authorization.swift
  Sources/ApodiniHTTPProtocol/Information/Expires.swift
  Sources/ApodiniHTTPProtocol/Information/HTTPHeaderKey.swift
  Sources/ApodiniHTTPProtocol/Information/HTTPInformation.swift
  Sources/ApodiniLoggingSupport/Logger.MetadataValue+Codable.swift
  Sources/ApodiniLoggingSupport/LoggingMetadataInformationClass.swift
  Sources/ApodiniObserve/Logs/ApodiniLogger.swift
  Sources/ApodiniObserve/Logs/LoggerConfiguration.swift
  Sources/ApodiniObserve/Logs/LoggerExporter.swift
  Sources/ApodiniREST/RESTEndpointHandler.swift
  Sources/ApodiniREST/RESTInterfaceExporter.swift
  Sources/ApodiniUtils/Other.swift
  Sources/ApodiniVaporSupport/Request+RequestBasis.swift
  Sources/ApodiniWebSocket/Infrastructure/Input.swift
  Sources/ApodiniWebSocket/WebSocketExporterConfiguration.swift
  Sources/ApodiniWebSocket/WebSocketInterfaceExporter.swift
  Sources/XCTApodini/Mocks/MockConnectionContext.swift
  Tests/ApodiniTests/GRPCInterfaceExporterTests.swift
  Tests/ApodiniTests/InformationTests/InformationRequestTests.swift
  Tests/ApodiniTests/InformationTests/InformationTests.swift
Labels: enhancement

#325 DocC Documentation and Articles
  .github/workflows/build-and-test.yml
  .github/workflows/docs.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yml
  .github/workflows/reuseaction.yml
  .github/workflows/spm-update.yml
  .github/workflows/swiftlint.yml
  .github/workflows/test-webservice.yml
  .gitignore
  .jazzy.yaml
  .swiftlint.yml
  CONTRIBUTORS.md
  Documentation/Semantic Model.md
  Package.resolved
  Package.swift
  Sources/Apodini/Apodini.docc/About/About.md
  Sources/Apodini/Apodini.docc/Advanced/BuildingExporters.md
  Sources/Apodini/Apodini.docc/Advanced/CommunicationPattern/CommunicationPattern.md
  Sources/Apodini/Apodini.docc/Advanced/CommunicationPattern/PatternImplementation/BidirectionalStream.md
  Sources/Apodini/Apodini.docc/Advanced/CommunicationPattern/PatternImplementation/ClientSideStream.md
  Sources/Apodini/Apodini.docc/Advanced/CommunicationPattern/PatternImplementation/PatternImplementation.md
  Sources/Apodini/Apodini.docc/Advanced/CommunicationPattern/PatternImplementation/RequestResponse.md
  Sources/Apodini/Apodini.docc/Advanced/CommunicationPattern/PatternImplementation/ServiceSideStream.md
  Sources/Apodini/Apodini.docc/Advanced/CommunicationPattern/Properties/MeaningOfEnvironment.md
  Sources/Apodini/Apodini.docc/Advanced/CommunicationPattern/Properties/MeaningOfObservedObject.md
  Sources/Apodini/Apodini.docc/Advanced/CommunicationPattern/Properties/MeaningOfParameter.md
  Sources/Apodini/Apodini.docc/Advanced/CommunicationPattern/Properties/MeaningOfState.md
  Sources/Apodini/Apodini.docc/Advanced/CommunicationPattern/Properties/Tooling.md
  Sources/Apodini/Apodini.docc/Advanced/DSLComponents.md
  Sources/Apodini/Apodini.docc/Advanced/ExporterConfiguration.md
  Sources/Apodini/Apodini.docc/Advanced/HandlerDelegation.md
  Sources/Apodini/Apodini.docc/Advanced/Proposals/RetrieveRelationship.md
  Sources/Apodini/Apodini.docc/Advanced/Semantic Model.md
  Sources/Apodini/Apodini.docc/Advanced/Testing/NegativeCompileTest.md
  Sources/Apodini/Apodini.docc/Apodini.md
  Sources/Apodini/Apodini.docc/Basics/AllAboutReuse.md
  Sources/Apodini/Apodini.docc/Basics/BuildingBlocks.md
  Sources/Apodini/Apodini.docc/Basics/Exporters/ProtocolBuffers.md
  Sources/Apodini/Apodini.docc/Basics/Exporters/WebSocket.md
  Sources/Apodini/Apodini.docc/Basics/Jobs.md
  Sources/Apodini/Apodini.docc/Basics/Operation.md
  Sources/Apodini/Apodini.docc/Basics/StatefulHandlers.md
  Sources/Apodini/Apodini.docc/Basics/UnitTesting.md
  Sources/Apodini/Apodini.docc/Ecosystem/DatabaseConnection.md
  Sources/Apodini/Apodini.docc/Ecosystem/PushNotifications.md
  Sources/Apodini/Apodini.docc/Extensions/Parameter.md
  Sources/Apodini/Apodini.docc/Extensions/PathParameter.md
  Sources/Apodini/Apodini.docc/GettingStarted/HelloWorld.md
  Sources/Apodini/Apodini.docc/GettingStarted/Installation.md
  Sources/Apodini/Components/ComponentBuilder.swift
  Sources/Apodini/Information/InformationInstantiatable.swift
  Sources/Apodini/Properties/Environment.swift
  Sources/Apodini/Properties/EnvironmentObject.swift
  Sources/Apodini/Semantic Model Builder/InterfaceExporter/InterfaceExporter.swift
  Sources/ApodiniExtension/ApodiniExtension.docc/ApodiniExtension.md
  codecov.yml
Labels: documentation, enhancement

#338 Migrating DeploymentOptions to Metadata System
  Sources/Apodini/Metadata/BuiltinContextKeys/OptionBasedMetadataContextKey.swift
  Sources/Apodini/Properties/Options/PropertyOption.swift
  Sources/Apodini/Properties/Options/PropertyOptionSet.swift
  Sources/ApodiniDeploy/ApodiniDeployExporterConfiguration.swift
  Sources/ApodiniDeploy/ApodiniDeployInterfaceExporter.swift
  Sources/ApodiniDeploy/DeploymentOptions/Condition.swift
  Sources/ApodiniDeploy/DeploymentOptions/ConditionalOption.swift
  Sources/ApodiniDeployBuildSupport/BuiltinOptions.swift
  Sources/ApodiniDeployBuildSupport/CollectedEndpointInfo.swift
  Sources/ApodiniDeployBuildSupport/DeployedSystem.swift
  Sources/ApodiniDeployBuildSupport/DeploymentOptions.swift
  Sources/ApodiniDeployBuildSupport/Metadata/DeploymentMemoryMetadata.swift
  Sources/ApodiniDeployBuildSupport/Metadata/DeploymentTimeoutMetadata.swift
  Sources/ApodiniDeployBuildSupport/Options/CollectedOptions.swift
  Sources/ApodiniDeployBuildSupport/Options/Namespace.swift
  Sources/ApodiniDeployBuildSupport/Options/OptionKey.swift
  Sources/ApodiniDeployBuildSupport/Options/OptionValue.swift
  Sources/ApodiniDeployRuntimeSupport/StructureExporter.swift
  Sources/ApodiniDeployTestWebService/ApodiniDeployTestWebService.swift
  Sources/ApodiniDeployTestWebService/Handler.swift
  Sources/ApodiniUtils/AnyEquatable.swift
  Sources/ApodiniUtils/Swift.swift
  Sources/DeploymentTargetAWSLambda/AWSIntegration.swift
  Sources/DeploymentTargetAWSLambdaCommon/LambdaCommon.swift
  Sources/DeploymentTargetAWSLambdaCommon/LambdaDescriptionMetadata.swift
  Sources/DeploymentTargetAWSLambdaRuntime/LambdaStructureExporterCommand.swift
  Tests/ApodiniDeployTests/ApodiniDeployInterfaceExporterTests.swift
  Tests/ApodiniDeployTests/DeploymentOptionsTests.swift
  Tests/ApodiniDeployTests/StructureExporterTests.swift
  Tests/ApodiniDeployTests/WebServiceStructureExportTests.swift
  Tests/ApodiniTests/Utilitites/AnyEncodableTests.swift
Labels: enhancement, needs version bump

#339 Allow for more detailed OpenAPI web service documentation through WebService Metadata
  Sources/Apodini/Metadata/BuiltinMetadata/CommunicationalPatternMetadata.swift
  Sources/Apodini/Metadata/BuiltinMetadata/DelegateMetadata.swift
  Sources/Apodini/Metadata/BuiltinMetadata/DescriptionMetadata.swift
  Sources/Apodini/Metadata/BuiltinMetadata/EmptyMetadata.swift
  Sources/Apodini/Metadata/BuiltinMetadata/GuardMetadata.swift
  Sources/Apodini/Metadata/BuiltinMetadata/OperationMetadata.swift
  Sources/Apodini/Metadata/BuiltinMetadata/ResetMetadata.swift
  Sources/Apodini/Metadata/BuiltinMetadata/ServiceTypeMetadata.swift
  Sources/Apodini/Metadata/BuiltinMetadata/WebServiceVersionMetadata.swift
  Sources/Apodini/Metadata/MetadataBlock.swift
  Sources/Apodini/Semantic Model Builder/KnowledgeSource.swift
  Sources/Apodini/Semantic Model Builder/KnowledgeSources/WebServiceContext.swift
  Sources/Apodini/SyntaxTreeVisitor/SyntaxTreeVisitor.swift
  Sources/Apodini/Version.swift
  Sources/Apodini/WebService.swift
  Sources/ApodiniOpenAPI/Document/OpenAPIDocumentBuilder.swift
  Sources/ApodiniOpenAPI/Document/OpenAPIPathsObjectBuilder.swift
  Sources/ApodiniOpenAPI/Metadata/WebService/ContactMetadata.swift
  Sources/ApodiniOpenAPI/Metadata/WebService/LicenseMetadata.swift
  Sources/ApodiniOpenAPI/Metadata/WebService/TagDescriptionMetadata.swift
  Sources/ApodiniOpenAPI/Metadata/WebService/TermsOfServiceMetadata.swift
  Sources/ApodiniOpenAPI/Metadata/WebService/WebServiceExternalDocumentationMetadata.swift
  Sources/ApodiniOpenAPI/OpenAPIExporterConfiguration.swift
  Sources/ApodiniOpenAPI/OpenAPIInterfaceExporter.swift
  Tests/ApodiniNegativeCompileTests/Cases/Metadata/RestrictedMetadata/RestrictedComponentMetadataTests.swift
  Tests/ApodiniTests/GRPCInterfaceExporterTests.swift
  Tests/ApodiniTests/MetadataTests/BuildinMetadata/DescriptionMetadataTests.swift
  Tests/ApodiniTests/MetadataTests/ComponentMetadataTests.swift
  Tests/ApodiniTests/MetadataTests/ContentMetadataTests.swift
  Tests/ApodiniTests/MetadataTests/WebServiceMetadataTests.swift
  Tests/ApodiniTests/ModifierTests/GuardTests.swift
  Tests/ApodiniTests/ModifierTests/OperationModifierTests.swift
  Tests/ApodiniTests/OpenAPITests/OpenAPIWebServiceMetadataTests.swift
Labels: enhancement, needs version bump

#340 Adding Metadata support to add OpenAPI Security schemes and requirements
  .github/workflows/build-and-test.yml
  .github/workflows/test-webservice.yml
  Package.swift
  Sources/ApodiniAuthorization/Delegates/AuthenticationScheme.swift
  Sources/ApodiniAuthorization/Delegates/Authenticator.swift
  Sources/ApodiniAuthorization/Delegates/AuthorizationRequirementsChecker.swift
  Sources/ApodiniAuthorizationBasicScheme/BasicAuthenticationScheme.swift
  Sources/ApodiniAuthorizationBearerScheme/BearerAuthenticationScheme.swift
  Sources/ApodiniAuthorizationJWT/MetadataExtensions/AuthorizationComponentMetadata+JWT.swift
  Sources/ApodiniAuthorizationJWT/MetadataExtensions/OptionalAuthorizationComponentMetadata+JWT.swift
  Sources/ApodiniOpenAPI/Document/OpenAPIComponentsObjectBuilder.swift
  Sources/ApodiniOpenAPI/Document/OpenAPIDocumentBuilder.swift
  Sources/ApodiniOpenAPI/Document/OpenAPIPathsObjectBuilder.swift
  Sources/ApodiniOpenAPI/Exports.swift
  Sources/ApodiniOpenAPI/Metadata/Component/Security/ApodiniSecurityType+OAuth2.swift
  Sources/ApodiniOpenAPI/Metadata/Component/Security/EndpointSecurityDescription.swift
  Sources/ApodiniOpenAPI/Metadata/Component/Security/Location+OpenAPI.swift
  Sources/ApodiniOpenAPI/Metadata/Component/Security/SecurityMetadata+init.swift
  Sources/ApodiniOpenAPI/Metadata/WebService/ContactMetadata.swift
  Sources/ApodiniOpenAPI/Metadata/WebService/LicenseMetadata.swift
  Sources/ApodiniOpenAPI/Metadata/WebService/TagDescriptionMetadata.swift
  Sources/ApodiniOpenAPI/Metadata/WebService/WebServiceExternalDocumentationMetadata.swift
  Sources/ApodiniOpenAPISecurity/ApodiniSecurityScheme.swift
  Sources/ApodiniOpenAPISecurity/ApodiniSecurityType.swift
  Sources/ApodiniOpenAPISecurity/Protocols/OpenAPISecurityScheme.swift
  Sources/ApodiniOpenAPISecurity/Protocols/OpenAPISecurityType.swift
  Sources/ApodiniOpenAPISecurity/Protocols/SomeSecurityDescription.swift
  Sources/ApodiniOpenAPISecurity/SecurityMetadata.swift
  Tests/ApodiniDeployTests/StructureExporterTests.swift
  Tests/ApodiniTests/InformationTests/InformationTests.swift
  Tests/ApodiniTests/OpenAPITests/OpenAPIComponentsObjectBuilderTests.swift
  Tests/ApodiniTests/OpenAPITests/OpenAPIDocumentBuilderTests.swift
  Tests/ApodiniTests/OpenAPITests/OpenAPIInterfaceExporterTests.swift
  Tests/ApodiniTests/OpenAPITests/OpenAPIPathsObjectBuilderTests.swift
  Tests/ApodiniTests/OpenAPITests/OpenAPISecurityMetadataTests.swift
Labels: enhancement
